name: iOS CI/CD

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build_ios:
    name: Build iOS (Simulator)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decode GoogleService-Info.plist
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_PLIST_BASE64 }}" | base64 --decode > iosApp/iosApp/GoogleService-Info.plist

      # 👈👈👈 این مرحله تو کد شما جا افتاده بود! (این جلوی اون ارور رو میگیره)
      - name: Generate Dummy Framework
        run: ./gradlew :composeApp:generateDummyFramework

      - name: Install CocoaPods
        run: |
          cd iosApp
          pod install

      - name: Build iOS App (No Signing)
        run: |
          cd iosApp
          xcodebuild -workspace iosApp.xcworkspace -scheme iosApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15' build CODE_SIGNING_ALLOWED=NO